# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15425e8dcfb0fb6ec1f95d91ad067b4eab2bda560b611468f38239c88fc96dd1fa5485a7516a4e03da6bbe3125d96ae20a68041a9f5cb420dc43763e08b6c6e1

test:
  secret_key_base: 3d2e4d52016e60c9524b241d347e54063152e3a7bc1e4e69dd216e75b69a778bdac43625f1d5537cd18a5540c87dbd231e5e210cdf556eea23ef2686da54e760

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
